name: "🐛 Bug Report"
description: Report something that isn't working as expected.
title: "FW-XXX: [Bug Title]"
labels: ["bug", "triage-needed"]

body:
  - type: markdown
    attributes:
      value: "## 📝 Description of the Bug"
  - type: textarea
    id: description
    attributes:
      description: "A clear and concise description of what the bug is."
      placeholder: "When I click the 'Save' button, the form data is not sent to the server, and the UI freezes."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🚶 Steps to Reproduce"
  - type: textarea
    id: steps
    attributes:
      description: "List the **exact** steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Log in with user 'test@example.com'
        3. Click on the 'Settings' tab
        4. Change the username field and click 'Save'
        5. Observe error/incorrect behavior
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## ✅ Expected Behavior"
  - type: textarea
    id: expected
    attributes:
      description: "What did you expect to happen?"
      placeholder: "The username should update successfully, and a 'Success' toast notification should appear."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## ❌ Actual Behavior"
  - type: textarea
  - type: textarea
    id: actual
    attributes:
      description: "What actually happened (e.g., error messages, wrong output)?"
      placeholder: "The application threw a '500 Internal Server Error' in the console, and the page didn't refresh."
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 🌎 Environment"
  - type: dropdown
    id: environment
    attributes:
      description: "Where did you observe the bug?"
      options:
        - Local Development
        - Staging
        - Production
        - Other (Please specify in the details below)
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## Browser"
  - type: input
    id: browser
    attributes:
      description: "e.g., Chrome 126, Firefox 110, Safari 17.5"
      placeholder: "Chrome 126"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "Operating System"
  - type: input
    id: os
    attributes:
      description: "e.g., macOS Sonoma, Windows 11, iOS 17"
      placeholder: "Windows 11"
    validations:
      required: true

  - type: markdown
    attributes:
      value: "## 📸 Screenshots or Console Logs"
  - type: textarea
    id: screenshots
    attributes:
      description: "Paste any relevant screenshots, animated GIFs, or console/server logs here."

  - type: markdown
    attributes:
      value: "## 💡 Possible Cause / Workaround"
  - type: textarea
    id: possible_cause
    attributes:
      description: "If you have an idea of what might be causing the bug or a temporary fix, please include it."
