name: "✨ Feature Request"
description: Suggest or specify a new feature or enhancement.
title: "FW-XXX: [Feature Title]"
labels: ["feature", "enhancement"]

body:
  # 1. Description Section
  - type: textarea
    id: description
    attributes:
      label: "## 📘 Description"
      description: "Describe the feature in detail — what it does, what problem it solves, and its purpose."
      placeholder: |
        Implement a secure, auditable consent system for minors. 
        When a user below 18 registers, their guardian receives a consent email. 
        The system must handle consent tokens, auditing, and deferred registration.
    validations:
      required: true

  # 2. Background / Context
  - type: textarea
    id: background
    attributes:
      label: "## 🧩 Background / Context"
      description: "Why is this feature needed? What problem, regulation, or scenario does it address?"
      placeholder: |
        To comply with COPPA/GDPR-K, minors must not gain full access until a guardian consents. 
        This system automates that flow and records consent for legal traceability.
    validations:
      required: true

  # 3. Acceptance Criteria
  - type: textarea
    id: acceptance
    attributes:
      label: "## ✅ Acceptance Criteria"
      description: "Define the measurable conditions that must be met for completion."
      placeholder: |
        - [x] When a user registers with age < 18, a guardian email is required.
        - [x] A guardian consent email is sent automatically.
        - [x] The consent link updates the minor’s profile when approved.
        - [x] The guardian must be registered and over 18.
        - [x] Tokens expire within 24–48 hours and cannot be reused.
    validations:
      required: true

  # 4. Implementation Notes
  - type: textarea
    id: implementation
    attributes:
      label: "## 🛠️ Implementation Notes"
      description: "Provide implementation or architectural notes, such as schema changes, Edge Functions, or email setup."
      placeholder: |
        * **Database:** Add `guardian_relationships` table with consent tracking fields.  
        * **Edge Function:** `send_guardian_consent_email` triggered on minor registration.  
        * **Email Service:** Integrate with Resend/SendGrid for transactional consent emails.  
        * **Frontend:** Add `/consent` page for deep link handling and token validation.  
        * **Security:** Hash tokens, enforce expiry, and log consent IPs and timestamps.
    validations:
      required: true

  # 5. Testing Notes
  - type: textarea
    id: testing
    attributes:
      label: "## 🧪 Testing Notes"
      description: "Describe the test plan, cases, and expected behavior."
      placeholder: |
        1. Register a user under 18 and provide a guardian email.  
        2. Verify the guardian receives a valid consent link.  
        3. Confirm consent updates the minor’s access.  
        4. Ensure expired or reused tokens fail securely.  
        5. Check that all consent events are logged correctly.
    validations:
      required: true

  # 6. Dependencies
  - type: textarea
    id: dependencies
    attributes:
      label: "## 🔗 Dependencies"
      description: "List all external dependencies, integrations, or prerequisite systems."
      placeholder: |
        * Supabase Edge Functions (v2)  
        * Resend or SendGrid integration  
        * Expo deep linking for consent URLs  
        * Database migration for guardian_relationships
    validations:
      required: false
