name: "🧠 Task"
description: Use this for internal technical or operational tasks, refactoring, or cleanup.
title: "FW-XXX: [Task Title]"
labels: ["task", "refactor", "operational"]

body:
  - type: textarea
    id: objective
    attributes:
      label: "## 🎯 Task Objective"
      description: "Clearly state what needs to be done. (e.g., 'Refactor the authentication hook to use Redux Toolkit' or 'Update all deployment manifests.')"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: "## 🛠️ Action Items / Checklist"
      description: "Break down the task into specific, manageable steps. Use a checklist format."
      placeholder: |
        - [ ] Create a new branch for the task
        - [ ] Apply changes to the configuration file X
        - [ ] Validate changes on the staging environment
        - [ ] Open a PR for review
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: "## 📜 Details / Context"
      description: "Provide necessary background, related internal documentation, or links to existing issues/PRs."

  - type: textarea
    id: acceptance
    attributes:
      label: "## ✅ Acceptance Criteria"
      description: "Define the specific, verifiable outcomes that confirm the task is complete and successful."
      placeholder: |
        - [ ] The refactored code passes all existing unit tests.
        - [ ] The new configuration is applied successfully in production.
        - [ ] No regressions or unexpected side effects are observed.
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "## 🔗 Dependencies & Blockers"
      description: "List any issues, pull requests, or prerequisites that must be completed before this task can start or be finished."
      placeholder: "Requires #123 (API update) to be merged first."
